/**
 * AutoReactiveClock - Demo using automatic ID generation
 *
 * This pattern uses a client wrapper that generates the ID and passes it
 * to the server component, eliminating manual ID management.
 */

import { useServerSignal, useServerEffect } from '../lib/server-hooks';

interface AutoReactiveClockProps {
  // The wrapper will pass this automatically
  _reactiveId?: string;
  interval?: number;
}

export async function AutoReactiveClock({
  _reactiveId = 'auto-clock',
  interval = 1000,
}: AutoReactiveClockProps) {
  if (!_reactiveId) {
    throw new Error('AutoReactiveClock must be wrapped with <Reactive>');
  }

  // Now we can use the auto-generated ID
  const [time, setTime] = await useServerSignal(_reactiveId, 'time', new Date().toISOString());
  const [ticks, setTicks] = await useServerSignal(_reactiveId, 'ticks', 0);

  await useServerEffect(_reactiveId, async () => {
    const intervalId = setInterval(() => {
      setTime(new Date().toISOString());
      setTicks((prev: number) => prev + 1);
    }, interval);

    return () => clearInterval(intervalId);
  }, [interval]);

  const formattedTime = new Date(time).toLocaleTimeString();

  return (
    <div className="p-4 bg-gradient-to-br from-green-50 to-teal-50 rounded border border-green-300">
      <h4 className="text-lg font-bold mb-3 text-green-800">
        🔄 Auto Clock (No Manual ID!)
      </h4>

      <div className="text-3xl font-mono font-bold text-green-900">
        {formattedTime}
      </div>

      <div className="mt-2 text-sm text-green-600">
        Ticks: <span className="font-bold">{ticks}</span>
      </div>

      <div className="mt-3 p-2 bg-white/50 rounded text-xs text-gray-600">
        ✨ ID auto-generated by wrapper: <code className="bg-white px-1">{_reactiveId}</code>
      </div>
    </div>
  );
}
